### ISSUE TITLE
improve javascript for hide/show

### ISSUE THREAD

**Issue by jonschlinkert** [upstage/showup#1]
@hbi99, want to help make this happen for the less.js website? This is a simple jquery plugin for hiding and showing a navbar on scroll, and it works okay but it has some issues that I'm hoping you can fix. 

Here is a live example: http://assemble.io/docs/helpers/index.html. 

Expected behavior:
- scroll down to hide the navbar. 
- scroll up to show  
- transitions to smooth out hiding and showing

The main issue it has currently is that when you "jump" to the top of a page the navbar doesn't appear. You have to manually scroll to make it appear. 

Ideally, this will be a nice jQuery plugin that has a few user-defined options:
- data-attribute or id of element to hide/show
- distance to scroll from top of page before hiding
- distance to scroll in general before hiding
- transition to apply to hide/show

What do you think? I'll just add you to this project if you're interested.

**Comment by bardtian** [comment]
Just like to know if any news about this?
:)
